package com.plcoding.oraclewms;

public enum FileMimeType {
    FILE_TYPE_IMAGE, FILE_TYPE_VIDEO, FILE_TYPE_AUDIO, FILE_TYPE_PDF, FILE_TYPE_TXT, FILE_TYPE_DOC, FILE_TYPE_DOCX, FILE_TYPE_XLS, FILE_TYPE_XLSX, FILE_TYPE_OTHER, FILE_TYPE_LIVE_STREAM
}
